# Plain text SSID/password is fine here.
# HolyConnect hashes the WPA key automatically when copying this config to the SD card.
country=PT
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="YOUR_WIFI_NAME"
    psk="YOUR_WIFI_PASSWORD"
    scan_ssid=1
}